### ISSUE TITLE
findlinks command not deleting Links

### ISSUE THREAD

**Issue by sbor23** [DjangoAdminHackers/django-linkcheck#101]
We're using the (not documented) setting `LINKCHECK_DISABLE_LISTENERS = True` to not have too much spam for normal save / delete during operation and testing.

We have a routine to call `findlinks` and subsequently `checklinks` periodically.
Now to our surprise this includes `Link`s to previously deleted instances.

https://github.com/DjangoAdminHackers/django-linkcheck/blob/a75cd57502a9fb1eac5e0a49c23f19a69a3ad4cd/linkcheck/utils.py#L142 doesn't seem to care about deleted links at all, but it will clean up deleted `Url`s.

Is this behaviour intended?

**Comment by andybak** [comment]
@fruitschen  ?

**Comment by timobrembeck** [comment]
We face the same issue and just drop the complete link database before scanning again - this makes it a bit cumbersome to restore the "ignored" status and leads to unnecessary re-checks of links, so I would be grateful if the findlinks could remove links which are no longer present in the content.
