### ISSUE TITLE
SSL certificates are not verified

### ISSUE THREAD

**Issue by timobrembeck** [DjangoAdminHackers/django-linkcheck#118]
Back in the day when this library was created, certificates weren't really a thing...
However, I think by now URLs with incorrect certificates should be marked as "invalid" rather than "valid", since all modern browsers refuse to open these URLs unless you accept the risk add an exception rule.

Is there a specific reason not to remove the `'verify': False,` here?
https://github.com/DjangoAdminHackers/django-linkcheck/blob/dfa053fbebd832e17de477dd9653472b775d0261/linkcheck/models.py#L280

**Comment by claudep** [comment]
Feel free to experiment and suggest a PR if you get some success!
