### ISSUE TITLE
Make status message translatable

### ISSUE THREAD

**Issue by timobrembeck** [DjangoAdminHackers/django-linkcheck#125]
We use this library in an app which is also used by people who aren't fluent in English, so we built [this workaround](https://github.com/digitalfabrik/integreat-cms/blob/307d495402e58822c33616227118de366fcd586e/integreat_cms/cms/templatetags/text_filters.py#L26-L44) in combination of [a fixed set of translatable strings](https://github.com/digitalfabrik/integreat-cms/blob/develop/integreat_cms/cms/constants/linkcheck.py) to translate the messages returned by linkcheck. It would be cool if this would be supported out of the box and I can imagine also other people would benefit from it.

Since most of the messages are a quite small set of messages, I think it shouldn't be too much effort to enable localization for them.
My suggestion would e.g. be to add constants for the messages like e.g.:
```
from django.utils.translation import ugettext_lazy as _

BROKEN_EXT_ANCHOR = "BROKEN_EXT_ANCHOR"
BROKEN_INT_ANCHOR = "BROKEN_INT_ANCHOR"
BROKEN_INT_LINK = "BROKEN_INT_LINK"
BROKEN_REDIRECT = "BROKEN_REDIRECT"
WORKING_REDIRECT = "WORKING_REDIRECT"
EMPTY_LINK = "EMPTY_LINK"
TIMEOUT = "TIMEOUT"
NOT_CHECKED = "NOT_CHECKED"

CHOICES = [
    (BROKEN_EXT_ANCHOR, _("Broken external hash anchor")),
    (BROKEN_INT_ANCHOR, _("Broken internal hash anchor")),
    (BROKEN_INT_LINK, _("Broken internal link")),
    (BROKEN_REDIRECT, _("Broken redirect")),
    (WORKING_REDIRECT, _("Working redirect")),
    (EMPTY_LINK, _("Empty link")),
    (TIMEOUT, _("Other Error: The read operation timed out")),
    (NOT_CHECKED, _("URL Not Yet Checked")),
    ...
]
```

and then reference those as choices for the message field:

```
message = models.CharField(choices=message.CHOICES, max_length=20, blank=True, null=True)
```

which means we would have to use `get_message_display()` to retrieve the readable value of the field.
And maybe for all "other errors" which are just a long exception message, maybe we add another field `verbose_message` or similar?

After that, users of the library who want to use it in their language can contribute translations for these texts.

What do you think about this approach?

**Comment by claudep** [comment]
Looks like a reasonable approach.
