### ISSUE TITLE
Releasing (sdist) does not include several folders 

### ISSUE THREAD

**Issue by claudep** [DjangoAdminHackers/django-linkcheck#146]
When trying to release 2.0.0 (`python setup.py sdist`), I realized that the build was not including folders like `management`, `migrations` and that `tests` was empty. Probably a regression in 918d2adfb0d (ping @timoludwig).

**Comment by timobrembeck** [comment]
Ah ok sorry, I just tested it with `python setup.py sdist bdist_wheel`... does this work for you? Or maybe the "new" `python -m build`?

**Comment by claudep** [comment]
We always released source-only for django-linkcheck, so only `python setup.py sdist`.

**Comment by timobrembeck** [comment]
Ok nevermind, even without building the wheel, `python setup.py sdist` works for me as well with python `3.10.8` and setuptools `62.1.0`.

**Comment by claudep** [comment]
I suspect we may be missing a `packages=find_packages()` line.

**Comment by claudep** [comment]
Indeed, with that line it works for me (I'm probably on an older Python setup than you (3.9)).

**Comment by timobrembeck** [comment]
Ok, interesting. Yeah sorry for the confusion, the [automatic discovery](https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#automatic-discovery) did just work fine for me, so I thought I could remove the config line.

**Comment by claudep** [comment]
Just released!
