### ISSUE TITLE
Reschedule checking of invalid links with HTTP status `429`/`529`

### ISSUE THREAD

**Issue by timobrembeck** [DjangoAdminHackers/django-linkcheck#153]
When links are invalid due to a server's rate limiting (usually denoted with HTTP status [`429`](https://http-status-code.de/429/)) or a temporary overload (unofficial standard seems to be [`529`](https://http.dev/529)), I think it would make sense to not update the (last) status of the link and keep `last_checked` unchanged. This way, the link can easier be checked again in the future even when `EXTERNAL_RECHECK_INTERVAL` has not yet passed.
Optionally, we could also re-schedule these tasks automatically as part of [cron.py](https://github.com/DjangoAdminHackers/django-linkcheck/blob/02c6db5d4bcc2db6480637a27314a59a2ba56c05/linkcheck/cron.py).

**Comment by claudep** [comment]
+1 to keep `last_checked` unchanged in this case.
