### ISSUE TITLE
PyPI release `2.2.0` does not contain locale files

### ISSUE THREAD

**Issue by timobrembeck** [DjangoAdminHackers/django-linkcheck#177]
The release https://pypi.org/project/django-linkcheck/2.2.0/ does not contain the compiled locale files.
In the manifest file they are listed:
https://github.com/DjangoAdminHackers/django-linkcheck/blob/b60394b85ce2107cd51ac83d7fb8e73d28e53802/MANIFEST.in#L5

So I guess the files were just not present on the machine on which the package was built?
Do we have a release guide documented somewhere where we could add this step?

I think it would be a suboptimal to add the compiled locale files to the repository, but maybe it's an acceptable trade off if it prevents this problem in the future?

**Comment by claudep** [comment]
2.2.1 was released, including translations.
