### ISSUE TITLE
Add index to `Link`

### ISSUE THREAD

**Issue by david-venhoff** [DjangoAdminHackers/django-linkcheck#202]
The [django documentation](https://docs.djangoproject.com/en/5.1/ref/contrib/contenttypes/#django.contrib.contenttypes.fields.GenericForeignKey) suggests to always create an index on the `content_type` and `object_id`  fields.
However, currently, there is no index for the `Link` model: https://github.com/DjangoAdminHackers/django-linkcheck/blob/d29f55b3f5fd790f4183bb2fe5eb67055f856f7e/linkcheck/models.py#L513 
At https://github.com/digitalfabrik/integreat-cms, a slow query using `Link` objects can be speed up about 40% by adding this index.

## Solution

Add this index to the `Link` model:

```python
    indexes = [
            models.Index(fields=["content_type", "object_id"]),
        ]
```

**Comment by claudep** [comment]
Good idea, would you like to suggest a patch?

**Comment by david-venhoff** [comment]
Sure, can do that :)
