### ISSUE TITLE
Urls reported as broken when actually they aren't.

### ISSUE THREAD

**Issue by dtrinchet** [DjangoAdminHackers/django-linkcheck#21]
Hi Andy, Thanks by this excelent app, undoubtedly very useful. 

I've been used it for a year or so, but in the last week I notice there are not working properly for some URLs, it seems something around googlecode hosting, you can try with this http://clementine-player.googlecode.com/files/ClementineSetup-1.1.1.exe.

Something similar are happening with ftp URLs, I'm aware of I must set up LINKCHECK_EXTERNAL_REGEX_STRING to a proper value so that this type of URL be consider as external, this is the one I've used r'^https?://|ftp://'. Here is something else, an exception is raising in the line self.message = ' '.join([str(response.code), response.msg]) of models.py module, the response come without the 'msg' attr despite that the URL is OK. Try this ftp://download.dosgamesarchive.com/omf2097.zip, for example.

I hope you can found a solution for this two issue, feel free let me know if I can help you with anything else, it will be a pleasure collaborate with you. 

Best wishes,
Trinchet

**Comment by claudep** [comment]
This is an old issue. If some similar issue can be reproduced with recent linkcheck code, please reopen!
