### ISSUE TITLE
Handling 301 redirects

### ISSUE THREAD

**Issue by claudep** [DjangoAdminHackers/django-linkcheck#35]
Currently, when an URL redirects with a 301 Permanent Redirect, linkcheck simply reports a "200 OK" status. This is because `urlopen()` follows the redirect and returns the code from the final URL.
By checking the `response.geturl()` result, we could detect that a redirection happened and report this redirect target to the `Url` model (in a new field?). Then we could propose in the admin interface a button to replace the old URL by the new one in the original model content.
Thoughts?

**Comment by andybak** [comment]
> Then we could propose in the admin interface a button to replace the old URL by the new one in the original model content.

Interesting although it's a step further than I've gone so far. It would bypass any custom logic in forms so it would need to be possible to disable it for cases where it wasn't safe.

We already have 'fix with redirect' button that automatically adds a contrib.redirect entry.

How would this feature interact with that?

**Comment by claudep** [comment]
> Interesting although it's a step further than I've gone so far. It would bypass any custom logic in forms so it would need to be possible to disable it for cases where it wasn't safe.

Good point about bypassing forms. However, considering this is an admin tool, and that we are simply replacing existing content, I don't see this as a major issue. The possibility to disable this behavior is a good idea anyway.

> We already have 'fix with redirect' button that automatically adds a contrib.redirect entry.
> How would this feature interact with that?

Could you point me to the code you are talking about? But in any case, `contrib.redirect` is not a solution at all for external links.

**Comment by claudep** [comment]
In this pull request, I just added and filled the new `redirect_to` field, and reported it in the report template. I'm still evaluating the ability to add a button to modify the original URL, but this is already a first step and the user can still copy-paste the new link if he wants.

**Comment by andybak** [comment]
> Could you point me to the code you are talking about?

Sorry - I was wrong. It was something we had planned but never implemented.

**Comment by claudep** [comment]
I have now updated PR #38 to only catch 301s.

**Comment by andybak** [comment]
Happy to merge this but I haven't had time to check out why the Travis build is failing. Is it something simple?

**Comment by claudep** [comment]
Oh, sorry, I didn't notice those failures. Will work on them.

**Comment by claudep** [comment]
Fixed now on Python 3 also.
