### ISSUE TITLE
Race condition in threaded signal handlers

### ISSUE THREAD

**Issue by claudep** [DjangoAdminHackers/django-linkcheck#41]
I have issues when I update objects, the `Urls` objects in `do_check_instance_links` always contain the previous URL content. I've struggled all afternoon on this. I'm unable to reproduce this behavior with tests, even when I force the threaded version of `do_check_instance_links`. The instances I'm getting from `get_linklist` are the old ones, but adding a `time.sleep(0.5)` just before that call, the instances are the good ones. So I suspect a race condition between the commit of the just-saved object and the query by `get_linklist` (might also be database-dependent, I'm using MySQL on Django 1.8).

Of course, `time.sleep` is a gross hack. Any idea about a cleaner solution?

**Comment by claudep** [comment]
Looks like https://code.djangoproject.com/ticket/21803 will be the final solution, but not for today.

**Comment by andybak** [comment]
It would be useful to see exactly what you're doing. Is this a feature you're adding to linkcheck itself or code outside of linkcheck?

**Comment by claudep** [comment]
I'm not doing anything special, that's what surprise me. Just a standard linkcheck config:

```
from linkcheck import Linklist
from ressource.models import Resource

class ResourceLinklist(Linklist):
    model = Resource
    url_fields = ['url', 'dl_url', 'emedia_url']
    ignore_empty = ['url', 'dl_url', 'emedia_url']

linklists = {'Ressources': ResourceLinklist}
```

**Comment by andybak** [comment]
How odd. I'm curious why we've never noticed. I'll take a look.

It does sound transaction related. A new thread will begin in a new transaction context and won't see the new changes.

I notice we're listening to pre_save. I don't suppose it's as simple as switching to post_save? I'm guessing that wouldn't always work depending on ATOMIC_REQUESTS.

What's your ATOMIC_REQUESTS setting?

**Comment by claudep** [comment]
It's happening with both values of ATOMIC_REQUESTS.
`do_check_instance_links` is hooked to post_save already.

**Comment by andybak** [comment]
I suppose the wait is an acceptable interim solution until we've got post_commit.

Alternatively - we could probably have some way to pushing the work onto a task queue. I'd like to avoid hardcoding a dependency on Celery but all we would do to provide was a command that did a unit of work and people could choose themselves how to trigger it.

**Comment by claudep** [comment]
About the task queue, I know there is also a probability that some basic task infrastructure might enter Django 1.9. So let's not rush. I'll experiment with a small wait time...
