### ISSUE TITLE
From optparse to argparse...

### ISSUE THREAD

**Issue by claudep** [DjangoAdminHackers/django-linkcheck#54]
In Django 1.10, management commands have to use argparse-based commands (they were introduced in Django 1.8). This is not such a big change, but the question is whether we want to keep supporting pre-Django 1.8 and write some compatibility layer, or if we can drop older and unsupported Django versions (namely 1.6 and 1.7)?

**Comment by andybak** [comment]
I've still got some legacy pre-1.8 sites in production but I suppose I would be happy to freeze them on an older version of linkcheck. 

How about deprecating in 1.3 and breaking compat in a 1.4? 

1.4 could simply contain the argparse rewrite and be released fairly soon after 1.3

**Comment by claudep** [comment]
The plan sounds good. I've just released 1.3, and will work on the argparse rewrite soon!
