### ISSUE TITLE
Worker/Queue system broken on latest linkcheck

### ISSUE THREAD

**Issue by claudep** [DjangoAdminHackers/django-linkcheck#69]
I was checking why some links weren't updated and realized than after restarting the server, only the first `do_check_instance_links` was actually called, it wasn't ever called for any subsequent object save :-(

**Comment by andybak** [comment]
That's odd. There's only two commits that could be the cause. 05c452d and 27e4240 and they both only affect the pre-save check. 

I'll investigate.

**Comment by claudep** [comment]
Apparently the worker_queue is never "dequeued", so after the first `put` on the queue, the queue is never empty so `start_worker` always quit.

**Comment by andybak** [comment]
The worker queue was added in January. Is it possible it was broken then and you hadn't noticed? It's possible on my side

**Comment by claudep** [comment]
Yes, most probably.

**Comment by andybak** [comment]
At first glance it seems as simple as adding tasks_queue.task_done() after the sleep in linkcheck_worker.

See if that fixes it. I'll try myself tomorrow if you don't get a chance.

**Comment by andybak** [comment]
@fruitschen FYI

**Comment by claudep** [comment]
> At first glance it seems as simple as adding tasks_queue.task_done() after the sleep in linkcheck_worker.

It doesn't seem to be the correct fix.

**Comment by andybak** [comment]
I've pushed a potential fix to feature/queue_fix 1e8eea14c8f8c4b8a1932d01f7c2f7933d21b696

Seems to work for me - let me know if you have a chance to try it.

**Comment by claudep** [comment]
Yes, looks like it's working for me too. Thanks!
