### ISSUE TITLE
Errors with long urls

### ISSUE THREAD

**Issue by andybak** [DjangoAdminHackers/django-linkcheck#75]
I noticed this when I ran checklinks on a site with a lot of old content. I'm seeing some crazy long redirects.

I've added an optional setting to have a longer redirect url length but this is challenging for migrations. I guess I need to write a manual migration outside of the linkcheck app.

Increasing the main link url above 255 is a problem due to MySQL not allowing unique constraints on varchars longer than this. My current problem is only with redirect urls however.

Even if I increase the limit, there is bound to be a longer redirect. So maybe we need a good failure behaviour for when this happens. Maybe just don't store the redirect? Or use a magic value and display it as "Redirect too long". In many cases the length is due to tracking cruft so maybe truncate the url to 252 and add a magic marker at the end to indicate it's been truncated. In many cases the truncated form would still work (thinking about it - we need to truncate intelligently - remove the last query param perhaps) 

That won't help if long non-redirect urls need to be handled. At the moment we fail loudly via manage.py but silently via model save signals (assuming they are async).

**Comment by andybak** [comment]
As a stop gap I'm going to truncate redirect urls to MAX_REDIRECT_URL_LENGTH

It's a poor solution but it's "less worse" than the current behaviour.

**Comment by claudep** [comment]
What prevents us to make `redirect_to` a TextField? AFAICS we don't have any index on this field.

**Comment by andybak** [comment]
Good point. Nothing really and it would be a one-time migration with no real downside.

It still leaves open the question of handling long non-redirect urls however. But that's currently theoretical as the defaults have worked fine for me so far. I guess users have more control over that in most cases - so it's easier to fix manually.

**Comment by claudep** [comment]
Are you going to work on a patch? Or else I may try to cook something…

**Comment by andybak** [comment]
I won't have time immediately so go for it.
