### ISSUE TITLE
Release django-linkcheck 1.5

### ISSUE THREAD

**Issue by claudep** [DjangoAdminHackers/django-linkcheck#81]
I'd like to have a new release soon. Here is a tentative CHANGELOG content:

* Added support for 'tel:' links.
* For redirecting links, linkcheck now reports the status of the redirect
  target (#78).
* Dropped South migrations.
* 'Url.redirect_to' was migrated to a TextField to not limit its length (#75).
* Fixed handling of the '--limit' argument of the 'checklinks' command (#73).
* Fixed the task queue of links to check (#69).

Any other suggestion?

**Comment by andybak** [comment]
I'm afraid I've rather been lost on Unity/VR world recently so haven't been watching closely. Unless @fruitschen has any suggestions that looks good to me.

**Comment by claudep** [comment]
Thanks, I still just want to get a green light for #80 before going further.

**Comment by andybak** [comment]
Sorry - I didn't spot that. I've just accepted that PR.

**Comment by claudep** [comment]
OK, 1.5 is out: https://pypi.python.org/pypi/django-linkcheck/1.5
