### ISSUE TITLE
Compatibility with Django 2.1

### ISSUE THREAD

**Issue by winged** [DjangoAdminHackers/django-linkcheck#84]
Django 2.1 reorganized some of it's middleware properties, causing the `checklinks` management command to fail:

```
...
  File "/home/dv/.pyenv/versions/elearning/lib/python3.6/site-packages/linkcheck/utils.py", line 23, in load_middleware
    for method in self._request_middleware:
AttributeError: 'LinkCheckHandler' object has no attribute '_request_middleware'
```

I think this needs to be rewritten to not depend on private (`_` prefixed) properties anymore.

**Comment by fruitschen** [comment]
Thanks for letting us know. It's fixed.
