### ISSUE TITLE
pip install fails: utf-8 can't encode character

### ISSUE THREAD

**Issue by awaelchli** [DjangoAdminHackers/django-linkcheck#87]
pip install fails for me. [Here](https://github.com/DjangoAdminHackers/django-linkcheck/files/2973131/pip.install.django-linkcheck.txt) is the full message.

Two errors appear at the same time:
`UnicodeEncodeError: 'utf-8' codec can't encode character '\udccc' in position 24: surrogates not allowed`

`UnicodeEncodeError: 'ascii' codec can't encode characters in position 73-74: ordinal not in range(128)`

Interestingly, if I install via git
`pip install git+git://github.com/DjangoAdminHackers/django-linkcheck.git`
i get a similar  
[message](https://github.com/DjangoAdminHackers/django-linkcheck/files/2973138/pip.install.git.txt), but only the first error is thrown. 

The issue looks  similar to issue #83, but the solution does not work. 
pip version: 19.0
Python: 3.4
django: 2.0.8

**Comment by claudep** [comment]
I'm almost sure it is related to the `rückmeldung` media test file written with both normalized and unnormalized unicode. #88 avoids that by only writing the tested file for the duration of the test.

**Comment by claudep** [comment]
Could you test installing by git again?

**Comment by awaelchli** [comment]
Installing by git works now! Thank you for the prompt fix!
