### ISSUE TITLE
Release django-linkcheck 1.6

### ISSUE THREAD

**Issue by claudep** [DjangoAdminHackers/django-linkcheck#89]
A new release would be great, to add support for latest Django versions.
@fruitschen, @andybak, any suggestions for the CHANGELOG?

**Comment by andybak** [comment]
I'll leave this to @fruitschen as I've been away from anything linkcheck related for quite a while.

Chen?

**Comment by fruitschen** [comment]
@claudep, please do it.

No suggestions. I've zero experience releasing anything on PyPi actually.

**Comment by claudep** [comment]
It's not about releasing, it's about what you would write in the CHANGELOG with regard to your commits since last release.

**Comment by fruitschen** [comment]
Use requests library when we get a 'certificate verify failed' error.

**Comment by fruitschen** [comment]
Use requests library when we get a 'certificate verify failed' error.
Fixed compatible issues with newer versions of Django.

**Comment by claudep** [comment]
Thanks for the suggestions.

**Comment by claudep** [comment]
1.6 is now released.
