### ISSUE TITLE
Drop support for Django < 1.11

### ISSUE THREAD

**Issue by claudep** [DjangoAdminHackers/django-linkcheck#90]
@DjangoAdminHackers/committers , after the 1.6 release, I would suggest to drop support for older Django versions. Would that be a problem for you?

**Comment by andybak** [comment]
We're cool with that. We might have some legacy sites still using Django 1.8 but it's up to us to maintain a branch/fork for them.

**Comment by claudep** [comment]
Do you mind if I reopen until a patch does that?

**Comment by andybak** [comment]
Sorry - yes. I was a bit hasty in closing this.
