### ISSUE TITLE
Do not mark link as broken when anchor is not found

### ISSUE THREAD

**Issue by claudep** [DjangoAdminHackers/django-linkcheck#98]
In some cases, anchors are not found in the page html source but the anchor is still valid and functional. For example, a youtube video where the anchor is used to set the seek point in the video.

I would suggest to not mark those links as broken, but just add a message like "Page OK but anchor was not found in page source". What do you think?

**Comment by andybak** [comment]
Would it work to make it configurable? We use this on sites where we definitely want this behaviour and I can imagine other sites where we might not.

That's certainly less work than adding a new status but a new status might be a better long-term solution. However it would be good to make sure it permeated correctly through the system so it was always actionable if needed.

**Comment by claudep** [comment]
I'm not sure to understand your last sentence, could you please clarify?

**Comment by andybak** [comment]
I guess I was saying "I don't have linkcheck in front of me right now but any new status would have to be reflected in the right places in the UI so that it was actually useful"
